project_id = "bizgybbywllbnuyvcaua"

[api]
enabled = true

[db]
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000/auth/callback",
  "http://localhost:3001/auth/callback",
  "http://localhost:3002/auth/callback"
]

[auth.external.google]
enabled = true
